<?php
$model = new Touch_TouchPayment_Model_Express();

//test the Touch system config if this button should be visible here
if(empty($model->getConfigData('visible_on_minicart'))){
    return;
}
$tokens = explode('/', $_SERVER['REQUEST_URI']);
// dc_todo: get this up there... mini cart
$touch = new Touch_TouchPayment_Block_Express_Button();
$touchEndpoint = $touch->getTouchUrl();
?>
<div id="touch_minicart_test"></div>

<script>
    (function() {
        var test = document.getElementById('touch_minicart_test');

        var newElementType = 'div';
        if(test.parentElement.nodeName == 'UL'){
            newElementType = 'li';
        }
        var newElement = document.createElement(newElementType);
        test.parentNode.insertBefore(newElement,test.nextSibling);

        //add div container
        var containerElem = document.createElement('div');
        containerElem.setAttribute('id', "top_cart_touch_button");
        newElement.appendChild(containerElem);

        <?php if($tokens[sizeof($tokens)-2] == "cart" || strpos($_SERVER['REQUEST_URI'],'checkout/cart') !== false){ //on cart page just render an empty div with this class - btn gets generated autom.?>
        var containerButton = document.createElement('div');
        containerButton.setAttribute('class', "touch-express-button");
        containerElem.appendChild(containerButton);
        <?php } else {?>
        //add script to load button
        var tag1 = document.createElement('SCRIPT');
        tag1.innerHTML = 'touchHost = "<?= $touchEndpoint; ?>";';
        containerElem.appendChild(tag1);

        //add script to load button
        var tag = document.createElement('SCRIPT');
        tag.setAttribute('src', "<?= $touchEndpoint; ?>/js/express.js");
        tag.setAttribute('class', "touch-express-button");
        tag.setAttribute('id', "touch-express-button");
        tag.setAttribute('data-url', "/touchredirect/express/index");
        tag.setAttribute('data-success-url', "/touchredirect");
        //tag.setAttribute('data-message', "Try before you buy");
        containerElem.appendChild(tag);
        <?php } ?>

        test.remove();
    })();
</script>